# Generated by Django 2.2.27 on 2022-04-02 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 2, 19, 25, 55, 16041), verbose_name='Опубликована'),
        ),
    ]
