# Generated by Django 2.2.27 on 2022-04-04 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220402_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 4, 10, 48, 3, 575050), verbose_name='Опубликована'),
        ),
    ]
